Repository PdxCodeGuild/HB3, pull requests merged in 2022-11, with the labels that each got.

#13 Newbranch
  code/Demond/readme.md
  code/Demond/test.py
Labels: 📝 - Review In Progress

#7 adding code file
  code/Brian/readme.md
Labels: 💯 - Review Complete

#18 Update 11 Your First Git Commit.md
  0 General/11 Your First Git Commit.md
Labels: 💯 - Review Complete

#19 Add a lab file and readme file
  code/eric/lab_00/README.md
Labels: 💯 - Review Complete

#22 completed lab 1
  code/Brian/Python/lab1_v1.py
  code/Brian/Python/lab1_v2.py
  code/Brian/Python/lab1_v3.py
  code/Brian/Python/lab1_v4.py
Labels: 📝 - Review In Progress

#34 Python lab 01
  code/eric/Python/lab_01_version_01.py
  code/eric/Python/lab_01_version_02 _03.py
  code/eric/Python/lab_01_version_04.py
  code/eric/lab_00/README.md
Labels: 💯 - Review Complete

#23 completed lab01
  code/matt-z/Python/Lab01_1.py
  code/matt-z/Python/Lab01_2.py
  code/matt-z/Python/Lab01_3.py
  code/matt-z/Python/Lab01_4.py
Labels: 📝 - Review In Progress

#30 all 4 labs version
  code/j_mondesir/python/unit_converter_ver1.py
  code/j_mondesir/python/unit_converter_ver2.py
  code/j_mondesir/python/unit_converter_ver3.py
  code/j_mondesir/python/unit_converter_ver4.py
Labels: 💯 - Review Complete

#24 finished lab1
  code/Russell/lab1_1.py
  code/Russell/lab1_2.py
  code/Russell/lab1_3.py
  code/Russell/lab1_4.py
Labels: 💯 - Review Complete

#26 Scott lefgren/lab01
  code/scott-l/python/lab01-version1.py
  code/scott-l/python/lab01-version2.py
  code/scott-l/python/lab01-version3.py
  code/scott-l/python/lab01-version4.py
Labels: 💯 - Review Complete

#32 Clement python lab01 final version
  code/Clement/pyhton_folder/lab01/unit_con_v1.py
  code/Clement/pyhton_folder/lab01/unit_con_v2.py
  code/Clement/pyhton_folder/lab01/unit_con_v3.py
  code/Clement/pyhton_folder/lab01/unit_con_v4.py
Labels: 💯 - Review Complete

#37 completed lab02
  code/matt-z/Python/Lab02_1.py
  code/matt-z/Python/Lab02_2.py
Labels: 📝 - Review In Progress

#40 Lab01 final
  code/.DS_Store
  code/kelsie/lab01/.DS_Store
  code/kelsie/lab01/kelsietwiss_lab1_1.py
  code/kelsie/lab01/kelsietwiss_lab1_2.py
  code/kelsie/lab01/kelsietwiss_lab1_3.py
  code/kelsie/lab01/kelsietwiss_lab1_4.py
  code/scott-l/python/.DS_Store
  code/scott-l/python/lab01-version1.py
Labels: 📝 - Review In Progress

#41 ver_1 lab2
  code/j_mondesir/python/number_to_phrase_v1.py
  code/j_mondesir/python/number_to_phrase_v2.py
Labels: 💯 - Review Complete

#46 completed lab03
  code/matt-z/Python/Lab03.py
Labels: 💯 - Review Complete

#50 cc_validation
  code/Clement/pyhton_folder/cc_validation.py
  code/Clement/pyhton_folder/lab03/cc_validation.py
Labels: 💯 - Review Complete

#62 Lab 2 v.2 - revised
  code/eric/Python/lab_02_version_02.py
Labels: 💯 - Review Complete

#45 Scott lefgren/02 lab
  code/scott-l/python/lab02-version1.py
  code/scott-l/python/lab02-version2.py
Labels: 💯 - Review Complete

#52 Lab01 versions 1-4
  code/AustinD/lab01v1.py
  code/AustinD/lab01v2.py
  code/AustinD/lab01v3.py
  code/AustinD/lab01v4.py
Labels: 📝 - Review In Progress

#53 kelsie twiss first attempt at lab 03
  code/kelsie/lab03/kelsietwiss_lab03.py
Labels: 💯 - Review Complete

#55 Daniel Lab01 + Practice01
  code/daniel/python/Lab01Dan.py
  code/daniel/python/Practice01Dan.py
Labels: 📝 - Review In Progress

#27 Daniel_Lab01
  code/daniel/python/Lab01Dan.py
  code/daniel/python/Lab02Dan.py
  code/daniel/python/Practice01Dan.py
Labels: Not Complete

#57 Daniel Lab03
  code/Daniel/Dan-Lab03.py
Labels: 💯 - Review Complete

#63 Scott lefgren/lab03
  code/scott-l/lab03.py
Labels: 💯 - Review Complete

#66 completed lab04
  code/matt-z/Python/Lab04.py
Labels: 💯 - Review Complete

#36 Lab01branch
  code/Demond/Python/lab01/lab01version1.py
  code/Demond/Python/lab01/lab01version2.py
  code/Demond/Python/lab01/lab01version3.py
  code/Demond/Python/lab01/lab01version4.py
  code/Demond/Python/lab02/lab02version1.py
  code/Demond/Python/lab02/lab02version2.py
Labels: ⚒️ - Changes Requested

#54 Lab3 russell
  code/Russell/01_numbers.py
  code/Russell/lab3_1.py
  code/Russell/test.py
Labels: ⚒️ - Changes Requested

#51 Mattp branch02
  code/mattp/python/lab01-version1.py
  code/mattp/python/lab01-version2.py
  code/mattp/python/lab01-version3.py
  code/mattp/python/lab01-version4.py
  code/mattp/python/lab02-version1.py
  code/mattp/python/lab02-version2.py
  code/mattp/python/lab03_version1.py
Labels: ⚒️ - Changes Requested
