Repository PdxCodeGuild/HB3, pull requests merged in 2022-12, with the labels that each got.

#69 russell lab4 finished
  code/Russell/lab4_1.py
Labels: 📝 - Review In Progress

#65 Mattp blackjack
  code/mattp/python/blackjack_lab04v1.py
  code/mattp/readme.md
Labels: 📝 - Review In Progress

#25 lab1ver1
  code/rachelb/python/lab1ver1.py
Labels: Not Complete

#70 Clement python lab04 black jack
  code/Clement/pyhton_folder/lab04/black_jack.py
  code/Clement/pyhton_folder/lab04/blackjack_opt.py
Labels: 📝 - Review In Progress

#72 Kelsie lab04
  code/kelsie/lab04/kelsietwiss_lab04_1.py
  code/kelsie/lab04/kelsietwiss_lab04_2.py
Labels: 📝 - Review In Progress

#80 Daniel Lab05
  code/daniel/dan_lab01_unit_converter.py
  code/daniel/dan_lab02_num_to_phrase.py
  code/daniel/dan_lab03_card_num_validation.py
  code/daniel/dan_lab04_blackjack.py
  code/daniel/dan_lab05_pick6.py
  code/daniel/dan_prac01_nums+arithmatic.py
Labels: 💯 - Review Complete

#82 Lab05 kelsie
  code/kelsie/lab05/lab05_kelsie.py
  code/kelsie/lab05/lab05_v2_kelsie.py
Labels: 📝 - Review In Progress

#96 Lab 3 - revised 3rd time
  code/eric/Python/lab_03.py
Labels: 📝 - Review In Progress

#77 completed lab05
  code/matt-z/Python/Lab05_1.py
  code/matt-z/Python/Lab05_2.py
Labels: 💯 - Review Complete

#97 Scott lefgren/lab05
  code/scott-l/python/lab05-version1.py
  code/scott-l/python/lab05-version2.py
Labels: 📝 - Review In Progress

#86 Lab 5 v 1 & 2
  code/eric/Python/lab_05_version_01_02.py
Labels: ⚒️ - Changes Requested, Ready For Review

#102 Update lab_04_version_02.py
  code/eric/Python/lab_04_version_02.py
Labels: Ready For Review

#95 lab05_pick6
  code/Clement/pyhton_folder/lab05/pick6.py
Labels: ⚒️ - Changes Requested

#83 DemondLab03
  code/Demond/Python/Lab3/Lab03.py
Labels: ⚒️ - Changes Requested

#101 Mattp pick6
  code/mattp/python/mattp_pick6lab.py
  code/mattp/python/mattp_pick6labV2.py
Labels: 💯 - Review Complete

#94 Lab4
  code/Demond/Python/Lab4/Lab4.py
  code/Demond/Python/lab01/lab01version1.py
  code/Demond/Python/lab01/lab01version2.py
  code/Demond/Python/lab01/lab01version3.py
  code/Demond/Python/lab01/lab01version4.py
  code/Demond/Python/lab02/lab02version1.py
  code/Demond/Python/lab02/lab02version2.py
Labels: 💯 - Review Complete

#103 Lab 6
  code/eric/Python/lab_06.py
Labels: Ready For Review

#116 lab7 dad jokes mob lab
  code/Russell/lab7_1.py
Labels: 💯 - Review Complete

#119 Scott lefgren/lab07
  code/scott-l/python/lab07.py
Labels: 💯 - Review Complete

#109 completed lab07
  code/matt-z/Python/Lab07_1.py
  code/matt-z/Python/Lab07_2.py
Labels: 💯 - Review Complete

#117 dad joke
  code/Clement/pyhton_folder/lab07/dad_joke.py
  code/Clement/pyhton_folder/lab07/dad_joke_v2.py
Labels: 💯 - Review Complete

#111 Lab 7v1
  code/eric/Python/lab_07_version_01.py
Labels: 💯 - Review Complete

#114 Daniel Lab07 Dad Joke API
  code/daniel/dan-lab01-unit-converter.py
  code/daniel/dan-lab02-num-to-phrase.py
  code/daniel/dan-lab03-card-num-validation.py
  code/daniel/dan-lab04-blackjack.py
  code/daniel/dan-lab05-pick6.py
  code/daniel/dan-lab07-dad-joke-API.py
  code/daniel/dan-prac01-nums+arithmatic.py
Labels: 💯 - Review Complete

#112 Dad jokes mob assignment
  code/AustinD/dad_jokes.py
Labels: 💯 - Review Complete

#108 completed lab08
  code/matt-z/Python/Lab08.py
Labels: 📝 - Review In Progress

#121 Austin lab03
  code/AustinD/lab03.py
  code/AustinD/requestsmoblab.py
Labels: ⚒️ - Changes Requested

#88 Rachel lab2
  code/rachelb/python/Lab1/lab1ver1.py
  code/rachelb/python/Lab2/lab2.py
Labels: 💯 - Review Complete

#99 Daniel Lab06 ARI
  code/Daniel/dan-lab06-ARI.py
Labels: 💯 - Review Complete

#115 so little of this is correct, yet
  code/Russell/lab8_1.py
  code/Russell/lab8_2.py
Labels: Not Complete

#120 Daniel Lab08 ATM
  code/daniel/dan-lab08-ATM.py
Labels: 💯 - Review Complete

#136 Lab 8v2
  code/eric/Python/lab_08_version_02.py
Labels: 💯 - Review Complete

#123 Lab 08 v 1
  code/eric/Python/lab_08_version_01.py
Labels: Ready For Review

#125 Jean dad jockes
  code/j_mondesir/python/dad_jokes.py
  code/j_mondesir/python/pick6.py
Labels: 💯 - Review Complete

#131 Austin lab04
  code/AustinD/lab04.py
Labels: 💯 - Review Complete

#130 Mattp arilab
  code/mattp/python/mattp_ARIlab.py
  code/mattp/python/stuff.txt
Labels: 💯 - Review Complete

#129 completed lab09
  code/matt-z/Python/Lab09.py
  code/matt-z/Python/contacts.json
Labels: 📝 - Review In Progress

#132 Scott lefgren/lab08
  code/scott-l/python/lab08.py
Labels: 📝 - Review In Progress

#118 Rachelb lab3
  code/rachelb/python/Lab4/lab4.py
  code/rachelb/python/lab3/lab3.py
Labels: 💯 - Review Complete

#110 completed lab06
  code/matt-z/Python/Lab06.py
Labels: 💯 - Review Complete

#142 Lab07 kelsie
  code/kelsie/lab07/dad_jokes_kelsie.py
  code/kelsie/lab07/dad_jokes_kelsie_v1.py
  code/kelsie/lab07/dad_jokes_kelsie_v2.py
Labels: 📝 - Review In Progress

#135 Daniel Lab09 Contact List
  code/daniel/dan-lab09-ContactList/contacts.json
  code/daniel/dan-lab09-ContactList/dan-lab09-ContactList.py
Labels: 📝 - Review In Progress

#137 completed lab10
  code/matt-z/Python/Lab10_1.py
  code/matt-z/Python/Lab10_2.py
Labels: 📝 - Review In Progress

#134 Austin lab05
  code/AustinD/dad_jokes.py
  code/AustinD/lab05v1.py
  code/AustinD/lab05v2.py
  code/AustinD/requestsmoblab.py
Labels: 💯 - Review Complete

#144 Daniel Lab10 Quotes API
  code/daniel/dan-lab01-DistUnitConverter.py
  code/daniel/dan-lab02-NumToPhrase.py
  code/daniel/dan-lab03-CardNumValidation.py
  code/daniel/dan-lab07-DadJokeAPI.py
  code/daniel/dan-lab10-QuotesAPI.py
Labels: 📝 - Review In Progress

#145 Demond lab08
  code/Demond/Python/Lab8/Lab8.py
  code/Demond/Python/Lab8/Lab8v2.py
Labels: 💯 - Review Complete

#147 completed lab11
  code/matt-z/Python/Lab11.py
Labels: 📝 - Review In Progress

#148 Scott lefgren/lab11
  code/scott-l/python/lab11-version1.py
Labels: 💯 - Review Complete

#150 Lab 11
  code/eric/Python/lab_11.py
Labels: 💯 - Review Complete

#152 Daniel Lab11 Jackalope Sim
  code/Daniel/dan-lab11-JackalopeSim.py
  code/daniel/dan-lab08-ATM.py
Labels: 💯 - Review Complete

#157 jackalopes
  code/Clement/pyhton_folder/lab11/jackalope.py
Labels: 💯 - Review Complete

#158 Lab07/Dad jokes mob lab
  code/AustinD/lab07.py
Labels: 💯 - Review Complete

#154 Lab 09
  code/eric/Python/contacts.json
  code/eric/Python/lab_09.py
Labels: 💯 - Review Complete

#155 Clement python lab10 qapi
  code/Clement/pyhton_folder/lab10/quot_v2api.py
  code/Clement/pyhton_folder/lab10/quotes_api.py
Labels: 📝 - Review In Progress

#161 Lab10 kelsie
  code/kelsie/lab07/dad_jokes_kelsie_v2.py
  code/kelsie/lab10/lab10_kelsie.py
  code/kelsie/lab10/lab10_kelsie_v2.py
Labels: 📝 - Review In Progress

#163 Austin lab06
  code/AustinD/lab06.py
Labels: 💯 - Review Complete

#164 Austin lab08
  code/AustinD/lab08.py
Labels: 📝 - Review In Progress

#128 Lab08 kelsie
  code/kelsie/lab07/dad_jokes_kelsie_v1.py
  code/kelsie/lab07/dad_jokes_kelsie_v2.py
  code/kelsie/lab08/lab08_kelsie.py
  code/kelsie/lab08/lab08_kelsie_v2.py
Labels: ⚒️ - Changes Requested

#141 Lab9 russell
  code/Russell/contacts.json
  code/Russell/lab9_1.py
  code/Russell/test.py
Labels: 💯 - Review Complete

#173 Rachelb lab6
  code/rachelb/python/Lab6/lab06.py
Labels: 📝 - Review In Progress

#167 Scott lefgren/lab09
  code/scott-l/python/contacts.json
  code/scott-l/python/lab09.py
  code/scott-l/python/lab09_contacts_list.py
Labels: 💯 - Review Complete

#171 Scott lefgren/lab10
  code/scott-l/python/lab10-version1.py
  code/scott-l/python/lab10-version2.py
Labels: 📝 - Review In Progress

#181 Mattp quotes lab
  code/mattp/python/mattp_quotes_labV1.py
  code/mattp/python/mattp_quotes_labV2.py
Labels: 📝 - Review In Progress

#182 Rachelb lab8
  code/rachelb/python/Lab8/lab8.py
Labels: 📝 - Review In Progress

#168 Jean atm
  code/j_mondesir/python/atm.py
  code/j_mondesir/python/atm_v2.py
Labels: ⚒️ - Changes Requested

#191 Austin lab09
  code/AustinD/lab09/contacts.json
  code/AustinD/lab09/lab09.py
Labels: 📝 - Review In Progress

#194 Lab09 kelsie
  code/kelsie/lab09/contacts.json
  code/kelsie/lab09/lab09_kelsie.py
  code/kelsie/lab09/new_contacts.json
Labels: 💯 - Review Complete

#196 Jean contactlist
  code/j_mondesir/python/contact_list.py
Labels: 💯 - Review Complete

#176 Demond lab10
  code/Demond/Python/Lab10/Lab10.py
  code/Demond/Python/Lab10/Lab10v2.py
Labels: ⚒️ - Changes Requested

#178 completed mini capstone
  code/matt-z/Python/mini_capstone.py
Labels: 💯 - Review Complete

#179 mincapst
  code/Clement/pyhton_folder/minicap/miniCapestone.py
Labels: 💯 - Review Complete

#172 Mini Capstone
  code/eric/Python/mini_capstone.py
  code/eric/Python/tesla_10k.pdf
Labels: 💯 - Review Complete

#195 Demond lab11
  code/Demond/Python/Lab11/lab11.py
Labels: 💯 - Review Complete

#198 Mattp/html: lab 01
  code/mattp/HTML/Lab01/Bailey Pup.jpg
  code/mattp/HTML/Lab01/mattp_lab01.html
Labels: 💯 - Review Complete

#143 too easy, drill sergeant!
  code/Russell/lab10_1.py
  code/Russell/lab10_2.py
Labels: ⚒️ - Changes Requested

#190 Austin lab10
  code/AustinD/lab10.py
  code/AustinD/lab10v2.py
Labels: 📝 - Review In Progress

#199 Austin mini capstone
  code/AustinD/MiniCapstone/MiniCaptstone.py
  code/AustinD/MiniCapstone/README.md
Labels: 📝 - Review In Progress

#187 Rachelb lab9
  code/rachelb/python/Lab9/Lab9.py
  code/rachelb/python/Lab9/contact_list.json
Labels: ⚒️ - Changes Requested

#201 bio_right_version
  code/Clement/flask_folder/lab01/Bill_Gates.jpg
  code/Clement/flask_folder/lab01/Gates.jpg
  code/Clement/flask_folder/lab01/bio.html
  code/Clement/flask_folder/lab01/style.css
Labels: 💯 - Review Complete

#203 Lab 02
  code/eric/HTML & CSS/group in suits.jpg
  code/eric/HTML & CSS/justice.jpg
  code/eric/HTML & CSS/lab_02.html
Labels: Ready For Review

#206 Scott lefgren/mini capstone
  code/scott-l/python/Mini_Capstone.md
  code/scott-l/python/Mini_Capstone.py
  code/scott-l/python/contacts.json
  code/scott-l/python/radio_station_list.json
Labels: 💯 - Review Complete

#207 Minicap kelsie
  code/kelsie/lab07/dad_jokes_kelsie_v1.py
  code/kelsie/lab07/dad_jokes_kelsie_v2.py
  code/kelsie/mini_capstone/maze_game_kelsie.py
Labels: 💯 - Review Complete

#213 Lab 04
  code/eric/HTML & CSS/lab_04.html
Labels: 💯 - Review Complete

#214 Demond mini capstone
  code/Demond/Python/Mini_Capstone/Mini_Capstone.py
  code/Demond/Python/Mini_Capstone/test.html
Labels: 💯 - Review Complete

#217 completed html/lab03
  code/matt-z/HTML/lab01/lab03/index.html
  code/matt-z/HTML/lab01/lab03/styles.css
Labels: 💯 - Review Complete

#210 Lab 03
  code/eric/HTML & CSS/lab_03.html
Labels: 💯 - Review Complete

#219 Mattp HTML Lab 02: Company
  code/mattp/HTML/Lab02/Peacock Pieces Design.png
  code/mattp/HTML/Lab02/PeacockFavicon.png
  code/mattp/HTML/Lab02/manet1.jpg
  code/mattp/HTML/Lab02/manet2.jpg
  code/mattp/HTML/Lab02/manet3.jpg
  code/mattp/HTML/Lab02/mattp_lab02.html
Labels: 💯 - Review Complete

#220 completed html/lab04
  code/matt-z/HTML/lab04/burrito.jpg
  code/matt-z/HTML/lab04/index.html
  code/matt-z/HTML/lab04/styles.css
Labels: 💯 - Review Complete

#212 Dan Lab01 Bio
  code/Daniel/html+css/dan-lab01-bio/dan-lab01-Bio.html
  code/Daniel/html+css/dan-lab01-bio/vermeer-girl-w-the-pearl.jpg
  code/Daniel/html+css/dan-lab01-bio/vermeer-self-potrait.jpeg
  code/Daniel/html+css/dan-lab01-bio/vermeer-view-of-delft.jpeg
  code/Daniel/python/dan-lab01-DistUnitConverter.py
  code/Daniel/python/dan-lab02-NumToPhrase.py
  code/Daniel/python/dan-lab03-CardNumValidation.py
  code/Daniel/python/dan-lab04-blackjack.py
  code/Daniel/python/dan-lab05-pick6.py
  code/Daniel/python/dan-lab06-ARI.py
  code/Daniel/python/dan-lab07-DadJokeAPI.py
  code/Daniel/python/dan-lab08-ATM.py
  code/Daniel/python/dan-lab09-ContactList/contacts.json
  code/Daniel/python/dan-lab09-ContactList/dan-lab09-ContactList.py
  code/Daniel/python/dan-lab10-QuotesAPI.py
  code/Daniel/python/dan-lab11-JackalopeSim.py
  code/Daniel/python/dan-prac01-nums+arithmatic.py
Labels: 💯 - Review Complete

#175 Daniel MiniCap HUD
  code/Daniel/dan-minicap-HUD/dan-minicap-QtHUD.py
  code/Daniel/dan-minicap-HUD/dan-minicap-TkHUD.py
Labels: 💯 - Review Complete

#221 rachelb_minicapstone_final
  code/rachelb/python/minicaps/minicaps.py
Labels: 💯 - Review Complete

#223 Minicapstone
  code/j_mondesir/python/password_generator.py
Labels: 📝 - Review In Progress

#225 Demond htmlcss lab1
  code/Demond/HTML&CSS/Lab1/Lab1.html
Labels: 📝 - Review In Progress

#228 Jean bio
  code/j_mondesir/html_css/bio.html
  code/j_mondesir/html_css/kevinHart.jpg
  code/j_mondesir/html_css/styles.css
Labels: 💯 - Review Complete
