Repository PdxCodeGuild/HB3, pull requests merged in 2023-01, with the labels that each got.

#229 Lab02html kelsie
  code/kelsie/lab02_HTML/Twiss_Kelsie_Headshot_Medium.jpeg
  code/kelsie/lab02_HTML/Waves_on_rocks_copy.jpg
  code/kelsie/lab02_HTML/Waves_on_rocks_copy_small.jpeg
  code/kelsie/lab02_HTML/boy_in_a_boat_small.jpeg
  code/kelsie/lab02_HTML/day_at_the_beach_copy_Small.jpeg
  code/kelsie/lab02_HTML/lab02html_kelsie.html
  code/kelsie/lab02_HTML/lily_lake_trail_small.jpeg
  code/kelsie/lab02_HTML/little_house_in_the_woods_copy_small.jpeg
  code/kelsie/lab02_HTML/mossy_path_small.jpeg
  code/kelsie/lab02_HTML/nighttime_2_small.jpeg
  code/kelsie/lab02_HTML/styles.css
  code/kelsie/lab02_HTML/the_writers_room_small.jpeg
  code/kelsie/lab02_HTML/wallace_river_2_small.jpeg
  code/kelsie/lab03_html/html_lab03_kelsie.html
Labels: 💯 - Review Complete

#230 Demond htmlcss lab2
  code/Demond/HTML&CSS/Lab2/lab2.html
Labels: 📝 - Review In Progress

#243 Lab03html kelsie
  code/kelsie/lab03_HTML/lab03html_kelsie
  code/kelsie/lab03_HTML/lab03html_kelsie.html
  code/kelsie/lab03_HTML/styles.css
Labels: ⚒️ - Changes Requested

#227 Clement flask lab04 burrito
  code/Clement/flask_folder/lab04/burrito.html
  code/Clement/flask_folder/lab04/image/burrito.jpg
  code/Clement/flask_folder/lab04/normalize.css
  code/Clement/flask_folder/lab04/style.css
Labels: 💯 - Review Complete

#249 Lab04html kelsie
  code/kelsie/lab04_HTML/brachi-burritos-final.jpg
  code/kelsie/lab04_HTML/burrito_order_kelsie.html
  code/kelsie/lab04_HTML/styles.css
Labels: 💯 - Review Complete

#252 Lab 4 15% complete
  code/Demond/HTML&CSS/Lab4/lab4.html
Labels: Not Complete

#264 FINISHED Lab 5: Flask (Unit Converter)
  code/mattp/HTML/Lab05/app.py
  code/mattp/HTML/Lab05/mattp_lab05.html
  code/mattp/HTML/Lab05/templates/index.html
  code/mattp/HTML/Lab05/templates/other.html
  code/mattp/python/lab01-version4.py
Labels: 📝 - Review In Progress

#266 Austin html/css lab05
  code/AustinD/Flask+HTML+CSS/lab05/app.py
  code/AustinD/Flask+HTML+CSS/lab05/templates/base.html
  code/AustinD/Flask+HTML+CSS/lab05/templates/index.html
Labels: ⚒️ - Changes Requested

#290 Lab 01 Part A
  code/eric/Javascript/Lab_01/Lab_01_Part_A1.html
  code/eric/Javascript/Lab_01/Lab_01_Part_A2.html
  code/eric/Javascript/Lab_01/Lab_01_Part_A3.html
Labels: Ready For Review
